spring.application.name=weatherpincode

# Server
server.port=8080

# Database - change username/password to yours
spring.datasource.url=jdbc:mysql://localhost:3306/weather_pincode
spring.datasource.username=root
spring.datasource.password=Sakshika2002@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA - auto creates tables for you
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# OpenWeather API Key - get free key from openweathermap.org
openweather.api.key=cd488781e2ae4bc9d56aa7d7526001cc